//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rawan
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEEE
    {
        public string ENAME { get; set; }
        public int EID { get; set; }
        public string EPOSITION { get; set; }
    }
}
